// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class Carrito
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public string NoParte { get; set; }
        public string TipoPrecio { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioU { get; set; }
        public decimal PrecioT { get; set; }
        public bool? Cerrado { get; set; }
        public string Proforma { get; set; }
        public DateTime? FechaIngreso { get; set; }
    }
}