// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class Dp03acom
    {
        public Dp03acom()
        {
            Dpinvcab = new HashSet<Dpinvcab>();
        }

        public string Codigo { get; set; }
        public string CodigoI { get; set; }
        public string CodigoE { get; set; }
        public string Nombre { get; set; }
        public string Main { get; set; }
        public string Tipo { get; set; }
        public string PideCosto { get; set; }
        public string Inventario { get; set; }
        public string Numero { get; set; }
        public string Forma { get; set; }
        public string Grupo { get; set; }
        public string Iva { get; set; }
        public string Items { get; set; }
        public string OcultaIva { get; set; }
        public string PermiteDescuento { get; set; }
        public bool? Integra { get; set; }
        public string TipoComprobanteContable { get; set; }
        public bool? GeneraNc { get; set; }
        public string TipoCredito { get; set; }
        public string TipoAplica { get; set; }
        public string PuntoVenta { get; set; }
        public string TipoRetencion { get; set; }
        public string Serie { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }
        public int IdEmpresa { get; set; }

        public virtual ICollection<Dpinvcab> Dpinvcab { get; set; }
    }
}