// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class Dp05a130
    {
        public Dp05a130()
        {
            Dp05acab = new HashSet<Dp05acab>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string Numero { get; set; }
        public bool? Integra { get; set; }
        public string TipoComprobanteContable { get; set; }
        public bool? GeneraNc { get; set; }
        public string TipoCredito { get; set; }
        public string CuentaDescuento { get; set; }
        public string CuentaIva { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }
        public int IdEmpresa { get; set; }

        public virtual ICollection<Dp05acab> Dp05acab { get; set; }
    }
}