// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class Dp05a120
    {
        public Dp05a120()
        {
            Dp05acab = new HashSet<Dp05acab>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string NombreCorto { get; set; }
        public string Entidad { get; set; }
        public bool? Numero { get; set; }
        public bool? CodigoBanco { get; set; }
        public bool? CuentaBanco { get; set; }
        public bool? PuntoVenta { get; set; }
        public string Cuenta { get; set; }
        public bool? Tarjeta { get; set; }
        public bool? GeneraNd { get; set; }
        public string TipoNd { get; set; }
        public bool? GeneraNc { get; set; }
        public string TipoNc { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }
        public int IdEmpresa { get; set; }

        public virtual ICollection<Dp05acab> Dp05acab { get; set; }
    }
}