// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class Dp06a150
    {
        public Dp06a150()
        {
            Dp06acab = new HashSet<Dp06acab>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Entidad { get; set; }
        public bool Numero { get; set; }
        public decimal UltimoNumero { get; set; }
        public bool CodigoBanco { get; set; }
        public bool CuentaBanco { get; set; }
        public string CuentaContable { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }
        public int IdEmpresa { get; set; }

        public virtual ICollection<Dp06acab> Dp06acab { get; set; }
    }
}