// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class Dpinvcab
    {
        public Dpinvcab()
        {
            Dp03amov = new HashSet<Dp03amov>();
            Dp05acab = new HashSet<Dp05acab>();
        }

        public long Id { get; set; }
        public string Tipo { get; set; }
        public string Numero { get; set; }
        public string NumeroB { get; set; }
        public string Referencia { get; set; }
        public string Grupo { get; set; }
        public string TipoT { get; set; }
        public DateTime Fecha { get; set; }
        public DateTime? FechaVencimiento { get; set; }
        public string BodegaDestino { get; set; }
        public string Bodega { get; set; }
        public long? IdEntidad { get; set; }
        public string Vendedor { get; set; }
        public string TipoPrecio { get; set; }
        public decimal? Subtotal { get; set; }
        public decimal? PorcentajeDescuento { get; set; }
        public decimal? TotalDescuento { get; set; }
        public decimal? PorcentajeIva { get; set; }
        public decimal? TotalIva { get; set; }
        public decimal? Total { get; set; }
        public string Comentario { get; set; }
        public string FacturaProveedor { get; set; }
        public string CodigoIngreso { get; set; }
        public string CodigoEgreso { get; set; }
        public string Asiento { get; set; }
        public string GuiaRemision { get; set; }
        public decimal? Base0 { get; set; }
        public decimal? BaseIva { get; set; }
        public string OrdenCompra { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }
        public int IdEmpresa { get; set; }

        public virtual Entidad IdEntidadNavigation { get; set; }
        public virtual Dp03acom TipoNavigation { get; set; }
        public virtual ICollection<Dp03amov> Dp03amov { get; set; }
        public virtual ICollection<Dp05acab> Dp05acab { get; set; }
    }
}