// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models
{
    public partial class Parroquia
    {
        public Parroquia()
        {
            Entidad = new HashSet<Entidad>();
        }

        public int Id { get; set; }
        public int IdCiudad { get; set; }
        public string Parroquia1 { get; set; }
        public decimal? Longitud { get; set; }
        public decimal? Latitud { get; set; }
        public string IpIngreso { get; set; }
        public string UsuarioIngreso { get; set; }
        public DateTime FechaIngreso { get; set; }
        public string IpModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public short IdEstado { get; set; }

        public virtual Ciudad IdCiudadNavigation { get; set; }
        public virtual ICollection<Entidad> Entidad { get; set; }
    }
}