// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataAccess.Repositories
{
    public partial interface IbenderbrauContextProcedures
    {
        Task<List<CarritoToProforResult>> CarritoToProforAsync(int? IdUsuario, string Bodega, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Custom_SecuencialResult>> Custom_SecuencialAsync(int? IdEmpresa, string xTipo, string xModulo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
