// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class AlptablaConfiguration : IEntityTypeConfiguration<Alptabla>
    {
        public void Configure(EntityTypeBuilder<Alptabla> entity)
        {
            entity.Property(e => e.Campo1)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Campo2)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");

            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");

            entity.Property(e => e.Gestion)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValueSql("('')")
                .IsFixedLength();

            entity.Property(e => e.Grupo)
                .HasMaxLength(70)
                .IsUnicode(false);

            entity.Property(e => e.IpIngreso)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.IpModificacion)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.Lencod).HasColumnType("decimal(2, 0)");

            entity.Property(e => e.Master)
                .HasMaxLength(5)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Nombre)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.Property(e => e.Nomtag)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(' ')");

            entity.Property(e => e.Sgrupo)
                .HasMaxLength(70)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioIngreso)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Valor)
                .HasColumnType("decimal(15, 2)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.Valor2).HasColumnType("decimal(16, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Alptabla> entity);
    }
}
