// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class Dp03amovConfiguration : IEntityTypeConfiguration<Dp03amov>
    {
        public void Configure(EntityTypeBuilder<Dp03amov> entity)
        {
            entity.HasIndex(e => e.Fecha, "fecha_tra");

            entity.Property(e => e.Bodega)
                .HasMaxLength(3)
                .IsUnicode(false);

            entity.Property(e => e.Cantidad)
                .HasColumnType("decimal(16, 2)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.CantidadDevuelta)
                .HasColumnType("decimal(16, 2)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.CentroCosto)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Consumo)
                .HasMaxLength(6)
                .IsUnicode(false)
                .HasDefaultValueSql("('')");

            entity.Property(e => e.CostoT)
                .HasColumnType("decimal(16, 4)")
                .HasColumnName("Costo_t")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.CostoU)
                .HasColumnType("decimal(16, 6)")
                .HasColumnName("Costo_u")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.DescuentoItem)
                .HasColumnType("decimal(6, 2)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.Despacho)
                .HasColumnType("decimal(16, 2)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.Devolucion).HasDefaultValueSql("((0))");

            entity.Property(e => e.Factor).HasColumnType("decimal(6, 0)");

            entity.Property(e => e.Fecha).HasColumnType("datetime");

            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");

            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");

            entity.Property(e => e.IpIngreso)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.IpModificacion)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.Lote)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Numero)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.PorcentajeDescuento)
                .HasColumnType("decimal(6, 2)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.PorcentajeIva)
                .HasColumnType("decimal(6, 2)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.PrecioNeto)
                .HasColumnType("decimal(16, 4)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.PrecioT)
                .HasColumnType("decimal(16, 4)")
                .HasColumnName("Precio_t")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.PrecioU)
                .HasColumnType("decimal(16, 4)")
                .HasColumnName("Precio_u")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.Presenta)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Serie).HasMaxLength(30);

            entity.Property(e => e.Servicio).HasMaxLength(250);

            entity.Property(e => e.Tipo)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TipoPrecio)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TipoT)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("Tipo_t")
                .IsFixedLength();

            entity.Property(e => e.Touch)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioIngreso)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ValorDescuento)
                .HasColumnType("decimal(16, 6)")
                .HasDefaultValueSql("((0))");

            entity.Property(e => e.ValorIva)
                .HasColumnType("decimal(16, 6)")
                .HasDefaultValueSql("((0))");

            entity.HasOne(d => d.IdComprobanteNavigation)
                .WithMany(p => p.Dp03amov)
                .HasForeignKey(d => d.IdComprobante)
                .HasConstraintName("FK_Dp03amov_Dpinvcab");

            entity.HasOne(d => d.IdProductoNavigation)
                .WithMany(p => p.Dp03amov)
                .HasForeignKey(d => d.IdProducto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Dp03amov_Dp03a110");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Dp03amov> entity);
    }
}
