// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class Dp05acabConfiguration : IEntityTypeConfiguration<Dp05acab>
    {
        public void Configure(EntityTypeBuilder<Dp05acab> entity)
        {
            entity.Property(e => e.Asiento)
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Cajero)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.CodigoBanco)
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasDefaultValueSql("('')")
                .IsFixedLength();

            entity.Property(e => e.Comenta)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.CuentaBanco)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValueSql("('')")
                .IsFixedLength();

            entity.Property(e => e.Fecha).HasColumnType("datetime");

            entity.Property(e => e.FechaDocumento)
                .HasColumnType("datetime")
                .HasDefaultValueSql("('1900-01-01')");

            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");

            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");

            entity.Property(e => e.FechaVencimiento).HasColumnType("datetime");

            entity.Property(e => e.IpIngreso)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.IpModificacion)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.Monto).HasColumnType("numeric(16, 2)");

            entity.Property(e => e.Numero)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.NumeroDocumento)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.NumeroPago)
                .HasMaxLength(20)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.TipoDocumento)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UsuarioIngreso)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdClienteNavigation)
                .WithMany(p => p.Dp05acab)
                .HasForeignKey(d => d.IdCliente)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Dp05acab_Dp05a110");

            entity.HasOne(d => d.IdFacturaNavigation)
                .WithMany(p => p.Dp05acab)
                .HasForeignKey(d => d.IdFactura)
                .HasConstraintName("FK_Dp05acab_Dpinvcab");

            entity.HasOne(d => d.IdTipoNavigation)
                .WithMany(p => p.Dp05acab)
                .HasForeignKey(d => d.IdTipo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Dp05acab_Dp05a130");

            entity.HasOne(d => d.IdTipoPagoNavigation)
                .WithMany(p => p.Dp05acab)
                .HasForeignKey(d => d.IdTipoPago)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Dp05acab_Dp05a120");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Dp05acab> entity);
    }
}
