// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class Dp06acabConfiguration : IEntityTypeConfiguration<Dp06acab>
    {
        public void Configure(EntityTypeBuilder<Dp06acab> entity)
        {
            entity.HasIndex(e => new { e.CodigoBanco, e.CuentaBanco, e.NumeroPago }, "BUSCA");

            entity.HasIndex(e => new { e.TipoDocumento, e.NumeroDocumento }, "DOCUM");

            entity.HasIndex(e => e.Fecha, "FECHA");

            entity.Property(e => e.Asiento)
                .HasMaxLength(10)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Cajero)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.CodigoBanco)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Comenta)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.CuentaBanco)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.FacturaProveedor)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.Fecha).HasColumnType("datetime");

            entity.Property(e => e.FechaDocumento).HasColumnType("datetime");

            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");

            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");

            entity.Property(e => e.FechaVencimiento).HasColumnType("datetime");

            entity.Property(e => e.IpIngreso)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.IpModificacion)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.Monto).HasColumnType("decimal(16, 4)");

            entity.Property(e => e.Numero)
                .IsRequired()
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.NumeroDocumento)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.NumeroPago)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.TipoDocumento)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.UsuarioIngreso)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.IdCompraNavigation)
                .WithMany(p => p.Dp06acab)
                .HasForeignKey(d => d.IdCompra)
                .HasConstraintName("FK_Dp06acab_Dpinvcab");

            entity.HasOne(d => d.IdProveedorNavigation)
                .WithMany(p => p.Dp06acab)
                .HasForeignKey(d => d.IdProveedor)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Dp06acab_Entidad");

            entity.HasOne(d => d.IdTipoNavigation)
                .WithMany(p => p.Dp06acab)
                .HasForeignKey(d => d.IdTipo)
                .HasConstraintName("FK_Dp06acab_Dp06a140");

            entity.HasOne(d => d.IdTipoPagoNavigation)
                .WithMany(p => p.Dp06acab)
                .HasForeignKey(d => d.IdTipoPago)
                .HasConstraintName("FK_Dp06acab_Dp06a150");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Dp06acab> entity);
    }
}
