// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataAccess.Models;
using DataAccess.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DataAccess.Repositories.Configurations
{
    public partial class EntidadConfiguration : IEntityTypeConfiguration<Entidad>
    {
        public void Configure(EntityTypeBuilder<Entidad> entity)
        {
            entity.HasIndex(e => e.Codigo, "codigo");

            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);

            entity.Property(e => e.Comenta)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Credito).HasColumnType("decimal(18, 0)");

            entity.Property(e => e.CuentaCliente)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.CuentaProveedor)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.DiasCredito).HasColumnType("numeric(3, 0)");

            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.EsContribuyente)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasDefaultValueSql("('N')");

            entity.Property(e => e.EstadoCivil)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.FechaIngreso).HasColumnType("datetime");

            entity.Property(e => e.FechaModificacion).HasColumnType("datetime");

            entity.Property(e => e.FechaNacimiento).HasColumnType("datetime");

            entity.Property(e => e.FechaUltimaCompra).HasColumnType("datetime");

            entity.Property(e => e.FechaUltimaVenta).HasColumnType("datetime");

            entity.Property(e => e.IpIngreso)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.IpModificacion)
                .HasMaxLength(15)
                .IsUnicode(false);

            entity.Property(e => e.NombreComercial)
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.PorcentajeDescuento).HasColumnType("decimal(6, 2)");

            entity.Property(e => e.Profesion)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.Property(e => e.RepresentanteCedula)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.RepresentanteLegal)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.RepresentanteTelefono)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Ruc)
                .IsRequired()
                .HasMaxLength(13)
                .IsUnicode(false);

            entity.Property(e => e.Sexo)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Telefono1)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.Telefono2)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.Property(e => e.TipoPrecio)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();

            entity.Property(e => e.Titulo)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioIngreso)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UsuarioModificacion)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.ValorUltimaCompra).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.ValorUltimaVenta).HasColumnType("decimal(16, 2)");

            entity.Property(e => e.Vendedor)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.IdCiudadNavigation)
                .WithMany(p => p.Entidad)
                .HasForeignKey(d => d.IdCiudad)
                .HasConstraintName("FK_Entidad_Ciudad");

            entity.HasOne(d => d.IdPaisNavigation)
                .WithMany(p => p.Entidad)
                .HasForeignKey(d => d.IdPais)
                .HasConstraintName("FK_Entidad_Pais");

            entity.HasOne(d => d.IdParroquiaNavigation)
                .WithMany(p => p.Entidad)
                .HasForeignKey(d => d.IdParroquia)
                .HasConstraintName("FK_Entidad_Parroquia");

            entity.HasOne(d => d.IdProvinciaNavigation)
                .WithMany(p => p.Entidad)
                .HasForeignKey(d => d.IdProvincia)
                .HasConstraintName("FK_Entidad_Provincia");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Entidad> entity);
    }
}
